### ISSUE TITLE
Text spacing issue.

### ISSUE THREAD

**Issue by Emmarie-Ahtunan** [MarcusOtter/CubeFlyer#4]
Text spacing issue:

<img width="593" alt="Screenshot 2023-05-01 at 1 36 10 PM" src="https://user-images.githubusercontent.com/86572370/235498857-acc70015-e997-42bb-8114-35ee3c3a4857.png">

**Comment by MarcusOtter** [comment]
@Emmarie-Ahtunan Great point! Taking resolution into account is important. It's probably not something we will fix in this repository as is it's meant as a template for people to get started with - this seems like it could be a perfect segue into UI responsiveness for people in their own projects. Good catch!
